# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    service_name:
        class: BackBundle\Services\GetForm
        arguments: ["@doctrine.orm.default_entity_manager","@form.factory"]
    import.csvtoarray:
        class: BackBundle\Services\ConvertCsvToArray
    askaffectationadv:
        class: BackBundle\EventListener\CreateUserEventListener
        arguments: ["@logger"]
        tags:
            - { name: doctrine.event_subscriber }
    app_user.Registration_Listener:
        class: BackBundle\EventListener\RegistrationListener
        arguments: []
        tags:
            - { name : kernel.event_subscriber}
    redirection:
        class: BackBundle\Services\Routing
        arguments: ["@Router"]
    application_backend.event_listener.message:
            class: BackBundle\EventListener\MessageListener
            arguments: ["@logger"]
            tags:
                - { name: kernel.event_listener, event: application_backend.event, method: onCreateMessage }

