<?php

namespace BackBundle\Repository;

/**
 * AdminisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminisRepository extends \Doctrine\ORM\EntityRepository
{
}
