<?php

namespace BackBundle\Repository;

/**
 * CmdHouseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CmdHouseRepository extends \Doctrine\ORM\EntityRepository
{
}
