<?php

namespace BackBundle\Repository;

/**
 * CmdQuotidienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CmdQuotidienRepository extends \Doctrine\ORM\EntityRepository
{
}
